# Generated by Django 4.2 on 2026-07-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0002_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
