# Generated by Django 4.2 on 2026-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0003_remove_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
