# Generated by Django 4.2 on 2026-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0006_alter_account_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.AddField(
            model_name='account',
            name='t24_customer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
