# Generated by Django 4.2 on 2026-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0007_remove_account_customer_account_t24_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contra_account',
            field=models.CharField(default=100000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='tet'),
            preserve_default=False,
        ),
    ]
