# Generated by Django 4.2 on 2026-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='t24_customer_accounts',
            field=models.CharField(blank=True, help_text="The unique ID of the customer's accounts in the T24 Core Banking System.", max_length=50, null=True, unique=True),
        ),
    ]
