# Generated by Django 4.2 on 2026-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_t24_customer_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='t24_customer_accounts',
            field=models.CharField(blank=True, help_text='Account numbers associated with the customer in the T24 Core Banking System.', max_length=50, null=True, unique=True),
        ),
    ]
